In [1]:
import pandas as pd

In [2]:
trans = pd.read_csv("transaction.csv")

In [3]:
trans.describe()

time         block
count  2.039147e+08  2.039147e+08
mean   1.507556e+09  4.399263e+06
std    1.528629e+07  9.630437e+05
min    0.000000e+00  0.000000e+00
25%    1.503040e+09  4.172327e+06
50%    1.512968e+09  4.712231e+06
75%    1.517247e+09  4.995088e+06
max    1.523431e+09  5.420000e+06

In [4]:
trans.columns

Index(['from', 'to', 'value', 'time', 'block'], dtype='object')

In [5]:
trans['from'][:5]

0    ethereum
1    ethereum
2    ethereum
3    ethereum
4    ethereum
Name: from, dtype: object

In [9]:
trans[['from','to','value']][trans['from']=='ethereum'][:5]

from                                        to                value
0  ethereum  0000000000000000000000000000000000000000  5000000000000000000
1  ethereum  05a56e2d52c817161883f50c441c3228cfe54d9f  5000000000000000000
2  ethereum  0193d941b50d91be6567c7ee1c0fe7af498b4137  5000000000000000000
3  ethereum  e6a7a1d47ff21b6321162aea7c6cb457d5476bca  5000000000000000000
4  ethereum  e6a7a1d47ff21b6321162aea7c6cb457d5476bca  5000000000000000000

In [12]:
len(trans['from'].unique())

24111011

In [15]:
len(trans['to'].unique())

27761796

In [14]:
len((trans['from']+trans['to']).unique())

73792000

In [17]:
t = trans[trans['to'] == '05a56e2d52c817161883f50c441c3228cfe54d9f']

In [18]:
len(t)

216

In [21]:
t_1 = trans['to'] == '05a56e2d52c817161883f50c441c3228cfe54d9f'
t_2 = trans['from'] == '05a56e2d52c817161883f50c441c3228cfe54d9f'
t = trans[t_1 | t_2]

In [22]:
t.head()

from  \
1                                       ethereum   
233991  e6a7a1d47ff21b6321162aea7c6cb457d5476bca   
385640                                  ethereum   
385727                                  ethereum   
627690  e6a7a1d47ff21b6321162aea7c6cb457d5476bca   

                                              to                value  \
1       05a56e2d52c817161883f50c441c3228cfe54d9f  5000000000000000000   
233991  05a56e2d52c817161883f50c441c3228cfe54d9f  3625798243899672600   
385640  05a56e2d52c817161883f50c441c3228cfe54d9f  5000000000000000000   
385727  05a56e2d52c817161883f50c441c3228cfe54d9f  5000000000000000000   
627690  05a56e2d52c817161883f50c441c3228cfe54d9f  2889119699486068700   

              time   block  
1       1438269988       1  
233991  1439885501  105316  
385640  1438345912   10797  
385727  1438344657   10710  
627690  1440011397  112684

In [23]:
len(t)

220

In [24]:
t.sort_values('block')

from  \
1                                          ethereum   
151907632                                  ethereum   
10705898                                   ethereum   
21721845                                   ethereum   
2937024                                    ethereum   
6390292                                    ethereum   
8064897                                    ethereum   
9841705                                    ethereum   
11038995                                   ethereum   
191207772                                  ethereum   
202334791                                  ethereum   
202352375                                  ethereum   
202615940                                  ethereum   
202753137                                  ethereum   
203031153                                  ethereum   
203241299                                  ethereum   
385727                                     ethereum   
385640                                     ethereum   
1272995                                    ethereum   
1272953                                    ethereum   
2289329                                    ethereum   
2422719                                    ethereum   
2624128                                    ethereum   
2624066                                    ethereum   
3245337                                    ethereum   
3580474                                    ethereum   
4111107                                    ethereum   
4206108                                    ethereum   
4206092                                    ethereum   
4763352                                    ethereum   
...                                             ...   
203052291  52bc44d5378309ee2abf1539bf71de1b7d7be3b5   
203057505  52bc44d5378309ee2abf1539bf71de1b7d7be3b5   
203066671  52bc44d5378309ee2abf1539bf71de1b7d7be3b5   
203072239  52bc44d5378309ee2abf1539bf71de1b7d7be3b5   
203081779  52bc44d5378309ee2abf1539bf71de1b7d7be3b5   
203091946  52bc44d5378309ee2abf1539bf71de1b7d7be3b5   
203096480  52bc44d5378309ee2abf1539bf71de1b7d7be3b5   
203164608  52bc44d5378309ee2abf1539bf71de1b7d7be3b5   
203169750  52bc44d5378309ee2abf1539bf71de1b7d7be3b5   
203180524  52bc44d5378309ee2abf1539bf71de1b7d7be3b5   
203188231  52bc44d5378309ee2abf1539bf71de1b7d7be3b5   
203196740  52bc44d5378309ee2abf1539bf71de1b7d7be3b5   
203208143  52bc44d5378309ee2abf1539bf71de1b7d7be3b5   
203213313  52bc44d5378309ee2abf1539bf71de1b7d7be3b5   
203223526  52bc44d5378309ee2abf1539bf71de1b7d7be3b5   
203228865  52bc44d5378309ee2abf1539bf71de1b7d7be3b5   
203240267  52bc44d5378309ee2abf1539bf71de1b7d7be3b5   
203246036  52bc44d5378309ee2abf1539bf71de1b7d7be3b5   
203262968  52bc44d5378309ee2abf1539bf71de1b7d7be3b5   
203269424  52bc44d5378309ee2abf1539bf71de1b7d7be3b5   
203280652  52bc44d5378309ee2abf1539bf71de1b7d7be3b5   
203285804  52bc44d5378309ee2abf1539bf71de1b7d7be3b5   
203296715  52bc44d5378309ee2abf1539bf71de1b7d7be3b5   
203301435  52bc44d5378309ee2abf1539bf71de1b7d7be3b5   
203312356  52bc44d5378309ee2abf1539bf71de1b7d7be3b5   
203316789  52bc44d5378309ee2abf1539bf71de1b7d7be3b5   
203328098  52bc44d5378309ee2abf1539bf71de1b7d7be3b5   
203333031  52bc44d5378309ee2abf1539bf71de1b7d7be3b5   
203343211  52bc44d5378309ee2abf1539bf71de1b7d7be3b5   
203904859  05a56e2d52c817161883f50c441c3228cfe54d9f   

                                                 to                  value  \
1          05a56e2d52c817161883f50c441c3228cfe54d9f    5000000000000000000   
151907632  05a56e2d52c817161883f50c441c3228cfe54d9f    5000000000000000000   
10705898   05a56e2d52c817161883f50c441c3228cfe54d9f    5000000000000000000   
21721845   05a56e2d52c817161883f50c441c3228cfe54d9f    5000000000000000000   
2937024    05a56e2d52c817161883f50c441c3228cfe54d9f    5000000000000000000   
6390292    05a56e2d52c817161883f50c441c3228cfe54d9f    5000000000000000000   
8064897    05a56e2d52c817161883f50c441c3228cfe54d9f    5000000000000000000   
9841705    0

In [26]:
trans[trans['from']=='05a56e2d52c817161883f50c441c3228cfe54d9f']

from  \
107737044  05a56e2d52c817161883f50c441c3228cfe54d9f   
107737077  05a56e2d52c817161883f50c441c3228cfe54d9f   
202925318  05a56e2d52c817161883f50c441c3228cfe54d9f   
203904859  05a56e2d52c817161883f50c441c3228cfe54d9f   

                                                 to                  value  \
107737044  1e2683322af6f316a53b6e7e3efd8f605ab2afcf  571485488822856522627   
107737077  1e2683322af6f316a53b6e7e3efd8f605ab2afcf      10000000000000000   
202925318  c130afe98f8c42e19bdacf8c6e63e48a44a26ca8                      1   
203904859  f94eee144446a9fe6e444dad9f69cd01954c0a34  116146791066933996608   

                 time   block  
107737044  1446414021  475329  
107737077  1446413541  475307  
202925318  1439399642   75212  
203904859  1455384054  998791

In [39]:
x = t[t['to']=='05a56e2d52c817161883f50c441c3228cfe54d9f']['value']

In [40]:
type(x)

pandas.core.series.Series

In [41]:
x = int(x)

TypeError: cannot convert the series to <class 'int'>

In [42]:
x = pd.to_numeric(x)

ValueError: Integer out of range. at position 108

In [43]:
x = x.astype(float)

In [44]:
x.sum()

6.21397066545064e+20

In [45]:
x.sum()/1000000000000000000

621.397066545064

In [46]:
t['value'] = t['value'].astype(float)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [47]:
t[t['to']=='05a56e2d52c817161883f50c441c3228cfe54d9f']['value'].sum()

6.21397066545064e+20

In [49]:
t[t['from']=='05a56e2d52c817161883f50c441c3228cfe54d9f']['value'].sum()

6.876422798897906e+20

In [50]:
symbols = ['+','-','/','*']

In [52]:
import numpy as np
symbols = np.array(symbols)
symbol_list = symbols[np.random.randint(len(symbols),size = 10000)]

In [53]:
symbol_list

array(['+', '-', '/', ..., '*', '-', '*'], dtype='<U1')

In [54]:
x = np.random.randint(1,11, size=10000)

In [55]:
y = np.random.randint(1,11, size=10000)

In [73]:
def evaluate(x,y,op):
    return eval (str(x) + op + str(y) )

In [75]:
a = np.vectorize(evaluate)

In [76]:
b = np.array([x,y,symbol_list])

In [77]:
a(*b)

array([ 8,  2,  2, ..., 30,  9, 18])

In [60]:
x

array([ 2,  7,  5, ...,  5, 10,  3])

In [61]:
y

array([6, 5, 2, ..., 6, 1, 6])

In [62]:
np.array([x,y,symbol_list])

array([['2', '7', '5', ..., '5', '10', '3'],
       ['6', '5', '2', ..., '6', '1', '6'],
       ['+', '-', '/', ..., '*', '-', '*']], dtype='<U21')

In [74]:
[evaluate(x,y,op) for x,y,op in zip(x,y,symbol_list)]

[8,
 2,
 2.5,
 2.0,
 1.6666666666666667,
 20,
 0.8888888888888888,
 10,
 60,
 5,
 18,
 21,
 1.1111111111111112,
 -4,
 56,
 2.0,
 20,
 4,
 21,
 9,
 11,
 0.6,
 1,
 0.8,
 56,
 72,
 6,
 1,
 15,
 48,
 3.5,
 2,
 50,
 0.5,
 10,
 80,
 12,
 -1,
 0.1111111111111111,
 10,
 14,
 14,
 9,
 25,
 5,
 1.0,
 3,
 6,
 30,
 63,
 2,
 14,
 9,
 1.0,
 18,
 1.0,
 0,
 0.8,
 0.125,
 -8,
 16,
 6,
 2.0,
 10,
 18,
 15,
 4,
 5,
 -5,
 4,
 16,
 -4,
 -3,
 6,
 0,
 4.0,
 32,
 4,
 8,
 15,
 36,
 3,
 1.6666666666666667,
 0.7,
 16,
 20,
 0,
 2,
 12,
 72,
 5,
 56,
 15,
 30,
 30,
 -4,
 13,
 10,
 3,
 4,
 -5,
 0.2857142857142857,
 -2,
 6,
 -4,
 1.0,
 0.8,
 50,
 50,
 11,
 0.2,
 48,
 15,
 -2,
 7,
 50,
 4,
 1.75,
 9,
 1.1111111111111112,
 0.14285714285714285,
 0.625,
 -4,
 0,
 2,
 15,
 12,
 0.16666666666666666,
 6.0,
 50,
 2.0,
 5,
 6,
 -8,
 1.8,
 13,
 90,
 10,
 5,
 -7,
 -5,
 11,
 9,
 0,
 8,
 0.16666666666666666,
 15,
 0.6666666666666666,
 1.0,
 6,
 1.125,
 36,
 -1,
 16,
 1.8,
 -3,
 10.0,
 -2,
 0.125,
 40,
 10,
 18,
 8,
 -7,
 0.5,
 

In [72]:
evaluate(1,2,'+')